sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t iaflleje/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iaflleje/react-test npm test

after_success:
  - docker build -t iaflleje/multi-client ./client
  - docker build -t iaflleje/multi-nginx ./nginx
  - docker build -t iaflleje/multi-server ./server
  - docker build -t iaflleje/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  # Take those images and push them to docker hub
  - docker push iaflleje/multi-client
  - docker push iaflleje/multi-nginx
  - docker push iaflleje/multi-server
  - docker push iaflleje/multi-worker


# # AWS
#   deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-2'
#   app: 'isra-docker'
#   env: 'IsraDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-2-704125407593'
#   bucket_path: 'docker-multi'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
